In [5]:
import numpy as np
# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими натуральними числами та виведіть його значення.
mat = np.random.randint(1, 101, size=(3, 3))
print(mat)

[[92 62  2]
 [74 28 55]
 [91 76 37]]


In [3]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
arr5x5 = np.random.uniform(-1, 1, (5, 5))
print(arr5x5)

[[ 0.54728805 -0.68745419  0.966206    0.78184782  0.8253829 ]
 [ 0.27662367  0.91910869  0.85242173 -0.78046601  0.5391319 ]
 [-0.1922047   0.46215553 -0.87816064  0.73605448 -0.75227957]
 [-0.73952875 -0.20216793 -0.90889949  0.43127054  0.87632541]
 [-0.39229794 -0.5326972   0.35822126  0.65195353 -0.96116711]]


In [4]:
# 4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє значення елементів.
arr = np.random.rand(5, 5)
print("Масив:\n", arr)
mean = np.mean(arr)
print("\nСереднє значення:", mean)

Масив:
 [[0.32088676 0.38062832 0.00539098 0.39783135 0.70987131]
 [0.89981269 0.16383031 0.99145192 0.42829139 0.50959237]
 [0.63724905 0.46004914 0.09427822 0.24058708 0.01967481]
 [0.30467962 0.07647282 0.26040886 0.35016563 0.59940381]
 [0.28200264 0.01421193 0.97525142 0.71675999 0.8192077 ]]

Середнє значення: 0.42631960449465295


In [6]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
# числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
arr1 = np.random.randint(-10, 11, 5)
arr2 = np.random.randint(-10, 11, 5)
print("Перший масив:", arr1)
print("Другий масив:", arr2)
sum_arr = arr1 + arr2
diff_arr = arr1 - arr2
prod_arr = arr1 * arr2
print("\nДодавання:", sum_arr)
print("Віднімання:", diff_arr)
print("Множення:", prod_arr)

Перший масив: [ 4  5  2  4 -5]
Другий масив: [ -3 -10   9   6  -9]

Додавання: [  1  -5  11  10 -14]
Віднімання: [ 7 15 -7 -2  4]
Множення: [-12 -50  18  24  45]


In [7]:
# 6. Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 3 до 10 та знайдіть їх добуток.
mat1 = np.random.uniform(3, 10, (2, 2))
mat2 = np.random.uniform(3, 10, (2, 2))
print("Перша матриця:\n", mat1)
print("Друга матриця:\n", mat2)
prod_mat = np.dot(mat1, mat2)
print("\nДобуток матриць:\n", prod_mat)

Перша матриця:
 [[8.47423969 8.45221633]
 [8.57976919 3.29929395]]
Друга матриця:
 [[3.44035187 5.39573478]
 [9.89359549 6.47283644]]

Добуток матриць:
 [[112.77717567 100.4345636 ]
 [ 62.1593047   67.64994908]]


In [9]:
# 7. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

mat1 = np.random.randint(1, 6, (2, 3))
mat2 = np.random.randint(1, 6, (3, 2))
print("Перша матриця (2x3):\n", mat1)
print("Друга матриця (3x2):\n", mat2)
prod_mat = np.dot(mat1, mat2)
print("\nДобуток матриць:\n", prod_mat)

Перша матриця (2x3):
 [[3 2 2]
 [5 1 4]]
Друга матриця (3x2):
 [[3 3]
 [4 2]
 [4 5]]

Добуток матриць:
 [[25 23]
 [35 37]]


In [10]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
mat = np.random.randint(1, 13, (3, 3))
print("Матриця 3x3:\n", mat)
if np.linalg.det(mat) != 0:
    inv_mat = np.linalg.inv(mat)
    print("\nОбернена матриця:\n", inv_mat)
else:
    print("\nМатриця не має оберненої матриці.")

Матриця 3x3:
 [[ 7  6  7]
 [ 3 11  1]
 [ 9  8  5]]

Обернена матриця:
 [[-0.20258621 -0.11206897  0.30603448]
 [ 0.02586207  0.12068966 -0.06034483]
 [ 0.32327586  0.00862069 -0.25431034]]


In [12]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -8 до 8 та транспонуйте її.
mat = np.random.uniform(-8, 8, (4, 4))
print("Матриця 4x4:\n", mat)
transp_mat = mat.T
print("\nТранспонована матриця:\n", transp_mat)

Матриця 4x4:
 [[ 2.02357291 -1.20811907  2.90115741 -1.69769999]
 [ 7.97232784 -0.14644862 -0.9729685  -5.69994604]
 [ 1.78480186 -2.16114556  4.4646492  -6.96106206]
 [ 4.27526739  4.31773244 -3.97133965  5.55217106]]

Транспонована матриця:
 [[ 2.02357291  7.97232784  1.78480186  4.27526739]
 [-1.20811907 -0.14644862 -2.16114556  4.31773244]
 [ 2.90115741 -0.9729685   4.4646492  -3.97133965]
 [-1.69769999 -5.69994604 -6.96106206  5.55217106]]


In [13]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
#цілими числами в діапазоні від 1 до 10 та знайдіть середнє значення елементів матриці.
mat = np.random.randint(1, 11, (3, 4))
vect = np.random.randint(1, 11, (4, 1))
print("Матриця 3x4:\n", mat)
print("\nВектор 4x1:\n", vect)
mean = np.mean(mat)
print("\nСереднє значення елементів матриці:", mean)

Матриця 3x4:
 [[ 2  3  5  9]
 [ 4 10  5  6]
 [ 7  4  2  1]]

Вектор 4x1:
 [[ 3]
 [10]
 [ 2]
 [ 7]]

Середнє значення елементів матриці: 4.833333333333333


In [14]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
#випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
#числами від 0 до 1, і знайдіть добуток матриці на вектор.
mat = np.random.randint(1, 11, (2, 3))
vect = np.random.uniform(0, 1, (3, 1))
print("Матриця 2x3:\n", mat)
print("\nВектор 3x1:\n", vect)
prod = np.dot(mat, vect)
print("\nДобуток матриці на вектор:\n", prod)

Матриця 2x3:
 [[ 7  6  4]
 [ 3  1 10]]

Вектор 3x1:
 [[0.1403313 ]
 [0.85840301]
 [0.73581486]]

Добуток матриці на вектор:
 [[9.07599661]
 [8.63754552]]


In [15]:
# 12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
mat1 = np.random.randint(1, 11, (3, 3))
mat2 = np.random.randint(1, 11, (3, 3))
print("Перша матриця 3x3:\n", mat1)
print("\nДруга матриця 3x3:\n", mat2)
diff_mat = mat1 - mat2
print("\nРізниця матриць:\n", diff_mat)

Перша матриця 3x3:
 [[ 7  6  8]
 [ 9  5  9]
 [ 6  9 10]]

Друга матриця 3x3:
 [[10  8  5]
 [ 9  3 10]
 [ 9  7  7]]

Різниця матриць:
 [[-3 -2  3]
 [ 0  2 -1]
 [-3  2  3]]


In [16]:
# 13. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
mat1 = np.random.randint(-5, 6, (3, 3))
mat2 = np.random.randint(-5, 6, (3, 3))
print("Перша матриця 3x3:\n", mat1)
print("\nДруга матриця 3x3:\n", mat2)
prod_mat = np.dot(mat1, mat2)
print("\nДобуток матриць:\n", prod_mat)

Перша матриця 3x3:
 [[ 1  1 -5]
 [ 2  2  2]
 [ 2 -2 -2]]

Друга матриця 3x3:
 [[-1 -4 -5]
 [ 3 -3  0]
 [ 0 -2  5]]

Добуток матриць:
 [[  2   3 -30]
 [  4 -18   0]
 [ -8   2 -20]]


In [17]:
# 14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від -5 до 5 та знайдіть суму елементів матриці.
mat = np.random.randint(-5, 6, (3, 3))
print("Матриця 3x3:\n", mat)
sum = np.sum(mat)
print("\nСума елементів матриці:", sum)

Матриця 3x3:
 [[ 1  1 -4]
 [ 5  2  2]
 [ 0 -1  3]]

Сума елементів матриці: 9


In [18]:
# 15. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
#діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів кожного рядка матриці.
mat = np.random.uniform(0, 1, (4, 4))
print("Матриця 4x4:\n", mat)
row_prods = np.prod(mat, axis=1)
col_vect = row_prods.reshape(-1, 1)
print("\nВектор-стовпчик з добутками елементів кожного рядка:\n", col_vect)

Матриця 4x4:
 [[0.02767346 0.2685695  0.21377578 0.39031613]
 [0.81709245 0.99490386 0.93941126 0.43727649]
 [0.26051748 0.46339658 0.13816948 0.33703501]
 [0.17818879 0.99444958 0.51425608 0.88843957]]

Вектор-стовпчик з добутками елементів кожного рядка:
 [[0.00062015]
 [0.33393673]
 [0.00562182]
 [0.08095999]]


Висновок:
На цій практичній роботі я пригадав елементи лінійної алгебри та застосування бібліотеки NumPy при роботі з матрицями.